spring.application.name=api

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true

ocr.engine.onnx.detection-model-path=classpath:models/ch_PP-OCRv4_det_infer.onnx
ocr.engine.onnx.recognition-model-path=classpath:models/korean_PP-OCRv4_rec_infer.onnx
ocr.engine.onnx.recognition-dictionary-path=classpath:models/korean_dict.txt
ocr.engine.onnx.detection-threshold=0.3

ocr.parser.column-separator-x=600
ocr.parser.y-offset=20
ocr.parser.y-deviation-threshold=75
ocr.parser.medicine-min-x=130
ocr.parser.medicine-max-x=260

notification.firebase.key-path=file:yak-allim-firebase-key.json